-- Carga inicial del catálogo real de productos de Carnes Patagonia. Hasta
-- ahora la tabla products solo tenía datos de prueba (QA-ASADO, ACH-001,
-- TEST-999) — Mostrador recién empezó a usarse de verdad y necesita un
-- catálogo real para poder vender. Códigos y nombres salen de la hoja
-- "PLANILLA CODIGOS" de la planilla del cliente (Planilla Patagonia Costos).
-- A pedido del cliente: unidad "kg" para todos por ahora (aunque algunos son
-- lógicamente "unit", ej. huevos, ofertas por caja) y costo/precio en 0 —
-- los precios de esa misma planilla estaban desactualizados, los va a cargar
-- él mismo después producto por producto desde la pantalla Stock.
-- on conflict do nothing: si se corre de nuevo, o si algún código ya
-- existiera, no pisa nada.
with target_company as (
  select p.company_id
  from public.profiles p
  join auth.users u on u.id = p.id
  where u.email = 'carnespatagoniaf@gmail.com'
)
insert into public.products (company_id, code, name, unit, cost, price_retail, min_stock, active)
select tc.company_id, v.code, v.name, 'kg', 0, 0, 0, true
from target_company tc, (values
  ('1', 'ROAST BEEF'),
  ('2', 'PALETA'),
  ('3', 'TORTUGUITA'),
  ('4', 'PALOMITA'),
  ('5', 'OSOBUCO'),
  ('6', 'OSOBUCO PREMIUN'),
  ('7', 'ESPINAZO'),
  ('8', 'PICADA COMUN'),
  ('9', 'PICADA ESPECIAL'),
  ('10', 'BIFE ANGOSTO'),
  ('11', 'BIFE ANCHO'),
  ('12', 'BIFE DE CHORIZO'),
  ('13', 'OJO DE BIFE'),
  ('14', 'LOMO'),
  ('15', 'TOMAHAWK'),
  ('16', 'ENTRAÑA'),
  ('17', 'ASADO'),
  ('18', 'ASADO DE PUNTA'),
  ('19', 'FALDA'),
  ('20', 'ASADO AMERICANO'),
  ('21', 'VACIO'),
  ('22', 'MATAMBRE VACUNO'),
  ('23', 'TAPA DE ASADO'),
  ('24', 'BIFE AMERICANO'),
  ('25', 'BOLA DE LOMO'),
  ('26', 'CUADRADA'),
  ('27', 'NALGA'),
  ('28', 'TAPA DE NALGA'),
  ('29', 'PECETO'),
  ('30', 'CUADRIL'),
  ('31', 'COLITA DE CUADRIL'),
  ('32', 'PICAÑA'),
  ('33', 'CHIQUIZUELA'),
  ('101', 'POLLO ENTERO'),
  ('102', 'SUPREMA'),
  ('103', 'PATA MUSLO'),
  ('104', 'PECHUGA'),
  ('105', 'ALITAS'),
  ('106', 'MENUDOS'),
  ('108', 'CARCAZA'),
  ('109', 'PATA MUSLO DESH'),
  ('201', 'BONDIOLA'),
  ('202', 'PECHITO'),
  ('203', 'MATAMBRE CERDO'),
  ('204', 'CARRE'),
  ('205', 'CARRE DESHUESADO'),
  ('206', 'RIBS'),
  ('207', 'ASADO AMERICANO CERDO'),
  ('208', 'SOLOMILLO'),
  ('209', 'BOLA DE LOMO CERDO'),
  ('210', 'CUADRADA CERDO'),
  ('211', 'NALGA CERDO'),
  ('212', 'PECETO CERDO'),
  ('213', 'CUADRIL CERDO'),
  ('214', 'PALOMITA CERDO'),
  ('215', 'TORTUGUITA CERDO'),
  ('216', 'ESPINAZO CERDO'),
  ('217', 'CHULETON CERDO'),
  ('218', 'PALETA CERDO'),
  ('219', 'PATITAS CERDO'),
  ('220', 'CUERITO CERDO'),
  ('221', 'OSOBUCO CERDO'),
  ('222', 'TAPA ASADO CERDO'),
  ('223', 'CHURRASQUITO CERDO'),
  ('224', 'CUERO'),
  ('301', 'CHINCHULIN'),
  ('302', 'MOLLEJA'),
  ('303', 'RIÑON'),
  ('304', 'HIGADO'),
  ('305', 'MONDONGO'),
  ('306', 'LENGUA'),
  ('307', 'RABO'),
  ('308', 'SESOS'),
  ('309', 'LENGUA AL ESCABECHE'),
  ('310', 'CORAZON'),
  ('311', 'T. GORDA'),
  ('312', 'CENTRO'),
  ('313', 'QUIJADA'),
  ('314', 'BOFE'),
  ('320', 'FILET'),
  ('401', 'CHORIZO CERDO'),
  ('402', 'CHORIZO MEZCLA'),
  ('403', 'CHORIZO CERDO PR'),
  ('404', 'PARRILLERA CERDO'),
  ('405', 'PARRILLERA MEZCLA'),
  ('406', 'MORCILLA'),
  ('407', 'MORCILLA VASCA'),
  ('408', 'SALCHICHA ALEMANA'),
  ('409', 'CHORIZO COLORADO'),
  ('501', 'HAMBURGUESA POLLO'),
  ('502', 'HAMBURGUESA CARNE'),
  ('503', 'HAMBURGUESA CERDO'),
  ('504', 'MILANESA POLLO'),
  ('505', 'MATAMBRE POLLO ELABORADO'),
  ('506', 'MILANESA CARNE ELABORADO'),
  ('507', 'MILANESA CERDO'),
  ('508', 'MATAMBRE CARNE'),
  ('509', 'ARROLLADO CARNE'),
  ('510', 'MATABRE ELABORADO CERDO'),
  ('511', 'MATAMBRE ELABORADO CARNE'),
  ('601', 'NUGGETS'),
  ('602', 'PATITAS'),
  ('603', 'CARITAS'),
  ('604', 'PAPAS TRADICIONAL'),
  ('605', 'RICOSAURIO'),
  ('606', 'MEDALLONES POLLO'),
  ('607', 'MUZZARELAS'),
  ('608', 'MEDALLON CRISPY'),
  ('609', 'BOCADOS CALABAZA'),
  ('610', 'BOCADOS ESPINACA'),
  ('611', 'NOISETTE'),
  ('612', 'MEDALLON JAMON Y QUESO'),
  ('613', 'PESCADO FILET CONGE'),
  ('614', 'CRISPY'),
  ('615', 'MILANESA SOJA'),
  ('616', 'AROS DE CEBOLLA'),
  ('701', 'HUEVO MEDIA DOCENA'),
  ('703', 'HUEVO MAPLE'),
  ('704', 'PAN RALLADO'),
  ('705', 'PROVOLETA NONA PIA'),
  ('723', 'QUESO GOUDA'),
  ('724', 'QUESO SARDO'),
  ('725', 'SALAME FUET'),
  ('726', 'SALAME PICADO FINO'),
  ('727', 'SALAME PICADO GRUESO'),
  ('728', 'PANCETA'),
  ('731', 'CHOR COLORADO ANG'),
  ('800', 'LECHON'),
  ('801', 'CORDERO'),
  ('802', 'CONEJO'),
  ('1001', 'OFERTA MILA POLLO 2KG'),
  ('1002', 'OFERTA ALITA 3KG'),
  ('1003', 'OFERTA ESPINAZO 3KG'),
  ('1004', 'OFERTA PATA MUSLO 3KG'),
  ('1005', 'OFERTA PALETA 2KG'),
  ('1006', 'OFERTA ROAST BEEF 2KG'),
  ('1007', 'OFERTA BOLA DE LOMO 2KG'),
  ('1008', 'OFERTA TAPA DE ASADO 2KG'),
  ('1009', 'OFERTA MENUDOS 3KG'),
  ('1010', 'OFERTA NALGA'),
  ('1011', 'OFERTA ASADO PUNT'),
  ('1012', 'OFERTA ASADO'),
  ('1013', 'OFERTA BIFE ANGOSTO'),
  ('1014', 'OFERTA BIFE ANCHO'),
  ('1015', 'OFERTA TAPA DE NALGA'),
  ('1016', 'OFERTA BIFE DE CHORIZO'),
  ('1017', 'OFERTA COLITA DE CUADRIL'),
  ('1018', 'OFERTA PICADA ESPECIAL'),
  ('1019', 'OFERTA CUADRADA'),
  ('1020', 'OFERTA PECETO'),
  ('1021', 'OFERTA LOMO'),
  ('1022', 'OFERTA CUADRIL'),
  ('1023', 'OFERTA PECHITO'),
  ('1024', 'OFERTA CARRE'),
  ('1025', 'OFERTA HAMBUR POLL/CARR'),
  ('1026', 'OFERTA MILA CARNE 2KG')
) as v(code, name)
on conflict (company_id, code) do nothing;
